add wp3 diagram
EVERSE-ResearchSoftware/EVERSE-ResearchSoftware.github.io pull request #13
Opened 2024-03-15 13:03 UTC by vuillaut

2024-03-15 16:18 UTC, graeme-a-stewart requested changes
Thanks @vuillaut. I would suggest that we structure the WP images just a bit differently. `assets/workpackages/wp3/...` is going to serve us better in the long run and help keep things easier to understand and manage.

2024-03-15 18:33 UTC, vuillaut commented
> Thanks @vuillaut. I would suggest that we structure the WP images just a bit differently. `assets/workpackages/wp3/...` is going to serve us better in the long run and help keep things easier to understand and manage.

I followed your suggestions, but maybe you meant in `assets/images/workpackages...` ?

2024-03-16 11:02 UTC, graeme-a-stewart commented
> > Thanks @vuillaut. I would suggest that we structure the WP images just a bit differently. `assets/workpackages/wp3/...` is going to serve us better in the long run and help keep things easier to understand and manage.
> 
> I followed your suggestions, but maybe you meant in `assets/images/workpackages...` ?

Oh damn! Yes, that is what I meant, it should be in `assets/images/...`. That's the danger of typing paths by hand.

Sorry for the confusion.

2024-03-19 06:57 UTC, graeme-a-stewart approved these changes

2024-03-19 06:57 UTC, merged